stages:
  - build
  - lint

default:
  image: node:lts-alpine

build:
  stage: build
  before_script:
    - apk add --no-cache build-base jpeg-dev zlib-dev automake autoconf libtool nasm libpng
    - npm i --force -g yarn
    - yarn install --frozen-lockfile
  script:
    - yarn build
  after_script:
    - yarn gulp clean
  artifacts:
    expire_in: 10 min
    paths:
      - node_modules/

prettier:
  stage: lint
  before_script:
    - npm i --force -g yarn
    - yarn install --frozen-lockfile
  script:
    - yarn prettier --check "src/**/*.{ts,js}"

stylelint:
  stage: lint
  before_script:
    - npm i --force -g yarn
    - yarn install --frozen-lockfile
  script:
    - yarn stylelint "src/**/*.{css,scss}"

tslint:
  stage: lint
  before_script:
    - npm i --force -g yarn
    - yarn install --frozen-lockfile
  script:
    - yarn tslint -c tslint.js "src/**/*.{ts,js}" -e "src/**/vendor?(s)/**/*"
